import { LearningWord } from '../types/learning-word.types';

export interface LearningWordFixture {
  id: string;
  word: string;
  promptLabel: string;
  accentColor: string;
  promptImage?: string;
  ipa: string[];
}

export const QUIZ_UNLOCK_THRESHOLD = 10;

export const LEARNING_WORDS: LearningWord[] = [
  {
    id: 'james',
    word: 'JAMES',
    promptLabel: 'James',
    accentColor: '#4A90E2',
    promptImage: '👦',
    ipa: ['dʒ', 'eɪ', 'm', '', 'z'],
  },
  {
    id: 'grandma',
    word: 'GRANDMA',
    promptLabel: 'Grandma',
    accentColor: '#C71585',
    promptImage: '👵',
    ipa: ['g', 'r', 'æ', 'n', 'd', 'm', 'ɑː'],
  },
  {
    id: 'grandad',
    word: 'GRANDAD',
    promptLabel: 'Grandad',
    accentColor: '#6C3483',
    promptImage: '👴',
    ipa: ['g', 'r', 'æ', 'n', 'd', 'æ', 'd'],
  },
  {
    id: 'mummy',
    word: 'MUMMY',
    promptLabel: 'Mummy',
    accentColor: '#E91E63',
    promptImage: '👩',
    ipa: ['m', 'ʌ', 'm', 'm', 'iː'],
  },
  {
    id: 'daddy',
    word: 'DADDY',
    promptLabel: 'Daddy',
    accentColor: '#27AE60',
    promptImage: '👨',
    promptPhoto: '/images/words/daddy.jpg',
    ipa: ['d', 'æ', 'd', 'd', 'iː'],
  },
  {
    id: 'sarah',
    word: 'SARAH',
    promptLabel: 'Sarah',
    accentColor: '#D6336C',
    promptImage: '👩‍🏻',
    ipa: ['s', 'eə', 'r', 'ə'],
  },
  {
    id: 'baby',
    word: 'BABY',
    promptLabel: 'Baby',
    accentColor: '#FFB6C1',
    promptImage: '👶',
    ipa: ['b', 'eɪ', 'b', 'iː'],
  },
  {
    id: 'grandpa',
    word: 'GRANDPA',
    promptLabel: 'Grandpa',
    accentColor: '#8B4513',
    promptImage: '👨‍🦳',
    ipa: ['g', 'r', 'æ', 'n', 'p', 'ɑː'],
  },
  {
    id: 'granny',
    word: 'GRANNY',
    promptLabel: 'Granny',
    accentColor: '#8E4585',
    promptImage: '👩‍🦳',
    ipa: ['g', 'r', 'æ', 'n', 'n', 'iː'],
  },
  {
    id: 'meg',
    word: 'MEG',
    promptLabel: 'Meg',
    accentColor: '#A0522D',
    promptImage: '🐕‍🦺',
    ipa: ['m', 'e', 'g'],
  },
  {
    id: 'dobson',
    word: 'DOBSON',
    promptLabel: 'Dobson',
    accentColor: '#3498DB',
    promptImage: '🏡',
    ipa: ['d', 'ɒ', 'b', 's', 'ə', 'n'],
  },
  {
    id: 'fox',
    word: 'FOX',
    promptLabel: 'Fox',
    accentColor: '#E67E22',
    promptImage: '🦊',
    ipa: ['f', 'ɒ', 'ks'],
  },
  {
    id: 'milk',
    word: 'MILK',
    promptLabel: 'Milk',
    accentColor: '#F8F9FA',
    promptImage: '🥛',
    ipa: ['m', 'ɪ', 'l', 'k'],
  },
  {
    id: 'orange',
    word: 'ORANGE',
    promptLabel: 'Orange',
    accentColor: '#F39C12',
    promptImage: '🍊',
    ipa: ['ɒ', 'r', 'ɪ', 'n', 'dʒ'],
  },
  {
    id: 'banana',
    word: 'BANANA',
    promptLabel: 'Banana',
    accentColor: '#F1C40F',
    promptImage: '🍌',
    ipa: ['b', 'ə', 'n', 'ɑː', 'n', 'ə'],
  },
  {
    id: 'dog',
    word: 'DOG',
    promptLabel: 'Dog',
    accentColor: '#8D5524',
    promptImage: '🐶',
    ipa: ['d', 'ɒ', 'g'],
  },
  {
    id: 'cat',
    word: 'CAT',
    promptLabel: 'Cat',
    accentColor: '#F2994A',
    promptImage: '🐱',
    ipa: ['k', 'æ', 't'],
  },
  {
    id: 'bike',
    word: 'BIKE',
    promptLabel: 'Bike',
    accentColor: '#E67E22',
    promptImage: '🚲',
    ipa: ['b', 'aɪ', 'k', ''],
  },
  {
    id: 'book',
    word: 'BOOK',
    promptLabel: 'Book',
    accentColor: '#2980B9',
    promptImage: '📗',
    ipa: ['b', 'ʊ', 'k'],
  },
  {
    id: 'tractor',
    word: 'TRACTOR',
    promptLabel: 'Tractor',
    accentColor: '#F39C12',
    promptImage: '🚜',
    ipa: ['t', 'r', 'æ', 'k', 't', 'ə'],
  },
  {
    id: 'crane',
    word: 'CRANE',
    promptLabel: 'Crane',
    accentColor: '#E67E22',
    promptImage: '🏗️',
    ipa: ['k', 'r', 'eɪ', 'n', ''],
  },
  {
    id: 'apple',
    word: 'APPLE',
    promptLabel: 'Apple',
    accentColor: '#E74C3C',
    promptImage: '🍎',
    ipa: ['æ', 'p', 'l', ''],
  },
  {
    id: 'jam',
    word: 'JAM',
    promptLabel: 'Jam',
    accentColor: '#CB4335',
    promptImage: '🫙',
    ipa: ['dʒ', 'æ', 'm'],
  },
  {
    id: 'big',
    word: 'BIG',
    promptLabel: 'Big',
    accentColor: '#2C3E50',
    promptImage: '🦕',
    ipa: ['b', 'ɪ', 'g'],
  },
  {
    id: 'splash',
    word: 'SPLASH',
    promptLabel: 'Splash',
    accentColor: '#3498DB',
    promptImage: '💦',
    ipa: ['s', 'p', 'l', 'æ', 'ʃ'],
  },
  {
    id: 'rain',
    word: 'RAIN',
    promptLabel: 'Rain',
    accentColor: '#5DADE2',
    promptImage: '🌧️',
    ipa: ['r', 'eɪ', 'n'],
  },
  {
    id: 'games',
    word: 'GAMES',
    promptLabel: 'Games',
    accentColor: '#8E44AD',
    promptImage: '🎲',
    ipa: ['g', 'eɪ', 'm', '', 'z'],
  },
  {
    id: 'jigsaw',
    word: 'JIGSAW',
    promptLabel: 'Jigsaw',
    accentColor: '#D35400',
    promptImage: '🧩',
    ipa: ['dʒ', 'ɪ', 'g', 's', 'ɔː'],
  },
  {
    id: 'tram',
    word: 'TRAM',
    promptLabel: 'Tram',
    accentColor: '#16A085',
    promptImage: '🚊',
    ipa: ['t', 'r', 'æ', 'm'],
  },
  {
    id: 'train',
    word: 'TRAIN',
    promptLabel: 'Train',
    accentColor: '#2980B9',
    promptImage: '🚂',
    ipa: ['t', 'r', 'eɪ', 'n'],
  },
  {
    id: 'rail',
    word: 'RAIL',
    promptLabel: 'Rail',
    accentColor: '#7F8C8D',
    promptImage: '🛤️',
    ipa: ['r', 'eɪ', 'l'],
  },
  {
    id: 'track',
    word: 'TRACK',
    promptLabel: 'Track',
    accentColor: '#5D6D7E',
    promptImage: '🚆',
    ipa: ['t', 'r', 'æ', 'k'],
  },

  // Level 6 additions
  {
    id: 'bus',
    word: 'BUS',
    promptLabel: 'Bus',
    accentColor: '#E67E22',
    promptImage: '🚌',
    ipa: ['b', 'ʌ', 's'],
  },
  {
    id: 'van',
    word: 'VAN',
    promptLabel: 'Van',
    accentColor: '#34495E',
    promptImage: '🚐',
    ipa: ['v', 'æ', 'n'],
  },
  {
    id: 'boat',
    word: 'BOAT',
    promptLabel: 'Boat',
    accentColor: '#2980B9',
    promptImage: '⛵',
    ipa: ['b', 'əʊ', '', 't'],
  },
  {
    id: 'car',
    word: 'CAR',
    promptLabel: 'Car',
    accentColor: '#C0392B',
    promptImage: '🚗',
    ipa: ['k', 'ɑː', ''],
  },

  // Level 7: Animals & Creatures
  {
    id: 'rat',
    word: 'RAT',
    promptLabel: 'Rat',
    accentColor: '#7F8C8D',
    promptImage: '🐀',
    ipa: ['r', 'æ', 't'],
  },
  {
    id: 'pig',
    word: 'PIG',
    promptLabel: 'Pig',
    accentColor: '#F48FB1',
    promptImage: '🐷',
    ipa: ['p', 'ɪ', 'g'],
  },
  {
    id: 'duck',
    word: 'DUCK',
    promptLabel: 'Duck',
    accentColor: '#F39C12',
    promptImage: '🦆',
    ipa: ['d', 'ʌ', 'k', ''],
  },
  {
    id: 'hen',
    word: 'HEN',
    promptLabel: 'Hen',
    accentColor: '#D35400',
    promptImage: '🐔',
    ipa: ['h', 'e', 'n'],
  },
  {
    id: 'frog',
    word: 'FROG',
    promptLabel: 'Frog',
    accentColor: '#27AE60',
    promptImage: '🐸',
    ipa: ['f', 'r', 'ɒ', 'g'],
  },
  {
    id: 'bat',
    word: 'BAT',
    promptLabel: 'Bat',
    accentColor: '#2C3E50',
    promptImage: '🦇',
    ipa: ['b', 'æ', 't'],
  },

  // Level 8: Nature, Outdoors & Animals
  {
    id: 'bug',
    word: 'BUG',
    promptLabel: 'Bug',
    accentColor: '#8E44AD',
    promptImage: '🐛',
    ipa: ['b', 'ʌ', 'g'],
  },
  {
    id: 'sun',
    word: 'SUN',
    promptLabel: 'Sun',
    accentColor: '#F1C40F',
    promptImage: '☀️',
    ipa: ['s', 'ʌ', 'n'],
  },
  {
    id: 'moon',
    word: 'MOON',
    promptLabel: 'Moon',
    accentColor: '#5DADE2',
    promptImage: '🌙',
    ipa: ['m', 'uː', '', 'n'],
  },
  {
    id: 'star',
    word: 'STAR',
    promptLabel: 'Star',
    accentColor: '#F39C12',
    promptImage: '⭐',
    ipa: ['s', 't', 'ɑː', ''],
  },
  {
    id: 'log',
    word: 'LOG',
    promptLabel: 'Log',
    accentColor: '#795548',
    promptImage: '🪵',
    ipa: ['l', 'ɒ', 'g'],
  },
  {
    id: 'web',
    word: 'WEB',
    promptLabel: 'Web',
    accentColor: '#95A5A6',
    promptImage: '🕸️',
    ipa: ['w', 'e', 'b'],
  },

  // Level 9: Things at Home & Clothes
  {
    id: 'hat',
    word: 'HAT',
    promptLabel: 'Hat',
    accentColor: '#2980B9',
    promptImage: '🧢',
    ipa: ['h', 'æ', 't'],
  },
  {
    id: 'cup',
    word: 'CUP',
    promptLabel: 'Cup',
    accentColor: '#D35400',
    promptImage: '☕',
    ipa: ['k', 'ʌ', 'p'],
  },
  {
    id: 'mug',
    word: 'MUG',
    promptLabel: 'Mug',
    accentColor: '#16A085',
    promptImage: '🥛',
    ipa: ['m', 'ʌ', 'g'],
  },
  {
    id: 'pot',
    word: 'POT',
    promptLabel: 'Pot',
    accentColor: '#C0392B',
    promptImage: '🍲',
    ipa: ['p', 'ɒ', 't'],
  },
  {
    id: 'pan',
    word: 'PAN',
    promptLabel: 'Pan',
    accentColor: '#7F8C8D',
    promptImage: '🍳',
    ipa: ['p', 'æ', 'n'],
  },
  {
    id: 'sock',
    word: 'SOCK',
    promptLabel: 'Sock',
    accentColor: '#9B59B6',
    promptImage: '🧦',
    ipa: ['s', 'ɒ', 'k', ''],
  },

  // Level 10: Fun Objects, Rich Alphabet & Sounds
  {
    id: 'box',
    word: 'BOX',
    promptLabel: 'Box',
    accentColor: '#D35400',
    promptImage: '📦',
    ipa: ['b', 'ɒ', 'ks'],
  },
  {
    id: 'zip',
    word: 'ZIP',
    promptLabel: 'Zip',
    accentColor: '#34495E',
    promptImage: '🤐',
    ipa: ['z', 'ɪ', 'p'],
  },
  {
    id: 'jet',
    word: 'JET',
    promptLabel: 'Jet',
    accentColor: '#2980B9',
    promptImage: '✈️',
    ipa: ['dʒ', 'e', 't'],
  },
  {
    id: 'yak',
    word: 'YAK',
    promptLabel: 'Yak',
    accentColor: '#8D6E63',
    promptImage: '🐂',
    ipa: ['j', 'æ', 'k'],
  },
  {
    id: 'tub',
    word: 'TUB',
    promptLabel: 'Tub',
    accentColor: '#1ABC9C',
    promptImage: '🛁',
    ipa: ['t', 'ʌ', 'b'],
  },
  {
    id: 'nut',
    word: 'NUT',
    promptLabel: 'Nut',
    accentColor: '#A0522D',
    promptImage: '🥜',
    ipa: ['n', 'ʌ', 't'],
  },

  // Level 11: 2-Syllable Toddler Favorites (Play & Pets)
  {
    id: 'teddy',
    word: 'TEDDY',
    promptLabel: 'Teddy',
    accentColor: '#D35400',
    promptImage: '🧸',
    ipa: ['t', 'e', 'd', '', 'iː'],
  },
  {
    id: 'puppy',
    word: 'PUPPY',
    promptLabel: 'Puppy',
    accentColor: '#8D5524',
    promptImage: '🐶',
    ipa: ['p', 'ʌ', 'p', '', 'iː'],
  },
  {
    id: 'kitten',
    word: 'KITTEN',
    promptLabel: 'Kitten',
    accentColor: '#F2994A',
    promptImage: '🐱',
    ipa: ['k', 'ɪ', 't', '', 'ə', 'n'],
  },
  {
    id: 'rabbit',
    word: 'RABBIT',
    promptLabel: 'Rabbit',
    accentColor: '#BDC3C7',
    promptImage: '🐰',
    ipa: ['r', 'æ', 'b', '', 'ɪ', 't'],
  },
  {
    id: 'button',
    word: 'BUTTON',
    promptLabel: 'Button',
    accentColor: '#34495E',
    promptImage: '🔘',
    ipa: ['b', 'ʌ', 't', '', 'ə', 'n'],
  },
  {
    id: 'pocket',
    word: 'POCKET',
    promptLabel: 'Pocket',
    accentColor: '#2980B9',
    promptImage: '👖',
    ipa: ['p', 'ɒ', 'k', '', 'ɪ', 't'],
  },

  // Level 12: 2-Syllable Machines, Vehicles & Animals
  {
    id: 'digger',
    word: 'DIGGER',
    promptLabel: 'Digger',
    accentColor: '#F39C12',
    promptImage: '🚜',
    ipa: ['d', 'ɪ', 'g', '', 'ə', ''],
  },
  {
    id: 'rocket',
    word: 'ROCKET',
    promptLabel: 'Rocket',
    accentColor: '#E74C3C',
    promptImage: '🚀',
    ipa: ['r', 'ɒ', 'k', '', 'ɪ', 't'],
  },
  {
    id: 'penguin',
    word: 'PENGUIN',
    promptLabel: 'Penguin',
    accentColor: '#2C3E50',
    promptImage: '🐧',
    ipa: ['p', 'e', 'ŋ', 'g', 'w', 'ɪ', 'n'],
  },
  {
    id: 'monkey',
    word: 'MONKEY',
    promptLabel: 'Monkey',
    accentColor: '#795548',
    promptImage: '🐒',
    ipa: ['m', 'ʌ', 'ŋ', 'k', 'iː', ''],
  },
  {
    id: 'tiger',
    word: 'TIGER',
    promptLabel: 'Tiger',
    accentColor: '#E67E22',
    promptImage: '🐯',
    ipa: ['t', 'aɪ', 'g', 'ə', ''],
  },
  {
    id: 'zebra',
    word: 'ZEBRA',
    promptLabel: 'Zebra',
    accentColor: '#34495E',
    promptImage: '🦓',
    ipa: ['z', 'e', 'b', 'r', 'ə'],
  },

  // Level 13: Consonant Digraphs (SH, CH, TH, NG)
  {
    id: 'ship',
    word: 'SHIP',
    promptLabel: 'Ship',
    accentColor: '#2980B9',
    promptImage: '🚢',
    ipa: ['ʃ', '', 'ɪ', 'p'],
  },
  {
    id: 'fish',
    word: 'FISH',
    promptLabel: 'Fish',
    accentColor: '#3498DB',
    promptImage: '🐟',
    ipa: ['f', 'ɪ', 'ʃ', ''],
  },
  {
    id: 'chick',
    word: 'CHICK',
    promptLabel: 'Chick',
    accentColor: '#F1C40F',
    promptImage: '🐥',
    ipa: ['tʃ', '', 'ɪ', 'k', ''],
  },
  {
    id: 'chair',
    word: 'CHAIR',
    promptLabel: 'Chair',
    accentColor: '#A0522D',
    promptImage: '🪑',
    ipa: ['tʃ', '', 'eə', '', ''],
  },
  {
    id: 'ring',
    word: 'RING',
    promptLabel: 'Ring',
    accentColor: '#F39C12',
    promptImage: '💍',
    ipa: ['r', 'ɪ', 'ŋ', ''],
  },
  {
    id: 'bath',
    word: 'BATH',
    promptLabel: 'Bath',
    accentColor: '#1ABC9C',
    promptImage: '🛁',
    ipa: ['b', 'ɑː', 'θ', ''],
  },

  // Level 14: Vowel Diphthongs & Special Vowels (OW, OI, OO, OR)
  {
    id: 'cow',
    word: 'COW',
    promptLabel: 'Cow',
    accentColor: '#795548',
    promptImage: '🐮',
    ipa: ['k', 'aʊ', ''],
  },
  {
    id: 'owl',
    word: 'OWL',
    promptLabel: 'Owl',
    accentColor: '#8D6E63',
    promptImage: '🦉',
    ipa: ['aʊ', '', 'l'],
  },
  {
    id: 'coin',
    word: 'COIN',
    promptLabel: 'Coin',
    accentColor: '#F1C40F',
    promptImage: '🪙',
    ipa: ['k', 'ɔɪ', '', 'n'],
  },
  {
    id: 'spoon',
    word: 'SPOON',
    promptLabel: 'Spoon',
    accentColor: '#95A5A6',
    promptImage: '🥄',
    ipa: ['s', 'p', 'uː', '', 'n'],
  },
  {
    id: 'fork',
    word: 'FORK',
    promptLabel: 'Fork',
    accentColor: '#7F8C8D',
    promptImage: '🍴',
    ipa: ['f', 'ɔː', '', 'k'],
  },
  {
    id: 'boot',
    word: 'BOOT',
    promptLabel: 'Boot',
    accentColor: '#8E44AD',
    promptImage: '🥾',
    ipa: ['b', 'uː', '', 't'],
  },

  // Level 15: Regular Plurals (Multi-Item Display)
  {
    id: 'cars',
    word: 'CARS',
    promptLabel: 'Cars',
    accentColor: '#C0392B',
    promptImage: '🚗',
    promptRepeat: 3,
    ipa: ['k', 'ɑː', '', 'z'],
  },
  {
    id: 'cups',
    word: 'CUPS',
    promptLabel: 'Cups',
    accentColor: '#D35400',
    promptImage: '☕',
    promptRepeat: 2,
    ipa: ['k', 'ʌ', 'p', 's'],
  },
  {
    id: 'cats',
    word: 'CATS',
    promptLabel: 'Cats',
    accentColor: '#F2994A',
    promptImage: '🐱',
    promptRepeat: 3,
    ipa: ['k', 'æ', 't', 's'],
  },
  {
    id: 'dogs',
    word: 'DOGS',
    promptLabel: 'Dogs',
    accentColor: '#8D5524',
    promptImage: '🐶',
    promptRepeat: 2,
    ipa: ['d', 'ɒ', 'g', 'z'],
  },
  {
    id: 'boats',
    word: 'BOATS',
    promptLabel: 'Boats',
    accentColor: '#2980B9',
    promptImage: '⛵',
    promptRepeat: 3,
    ipa: ['b', 'əʊ', '', 't', 's'],
  },
  {
    id: 'ducks',
    word: 'DUCKS',
    promptLabel: 'Ducks',
    accentColor: '#F39C12',
    promptImage: '🦆',
    promptRepeat: 4,
    ipa: ['d', 'ʌ', 'k', '', 's'],
  },

  // Level 16: Irregular Plurals (Multi-Item Display)
  {
    id: 'boxes',
    word: 'BOXES',
    promptLabel: 'Boxes',
    accentColor: '#D35400',
    promptImage: '📦',
    promptRepeat: 2,
    ipa: ['b', 'ɒ', 'ks', 'ɪ', 'z'],
  },
  {
    id: 'buses',
    word: 'BUSES',
    promptLabel: 'Buses',
    accentColor: '#E67E22',
    promptImage: '🚌',
    promptRepeat: 3,
    ipa: ['b', 'ʌ', 's', 'ɪ', 'z'],
  },
  {
    id: 'sheep',
    word: 'SHEEP',
    promptLabel: 'Sheep',
    accentColor: '#BDC3C7',
    promptImage: '🐑',
    promptRepeat: 4,
    ipa: ['ʃ', '', 'iː', '', 'p'],
  },
  {
    id: 'feet',
    word: 'FEET',
    promptLabel: 'Feet',
    accentColor: '#E67E22',
    promptImage: '🦶',
    promptRepeat: 2,
    ipa: ['f', 'iː', '', 't'],
  },
  {
    id: 'teeth',
    word: 'TEETH',
    promptLabel: 'Teeth',
    accentColor: '#3498DB',
    promptImage: '🦷',
    promptRepeat: 3,
    ipa: ['t', 'iː', '', 'θ', ''],
  },
  {
    id: 'mice',
    word: 'MICE',
    promptLabel: 'Mice',
    accentColor: '#7F8C8D',
    promptImage: '🐁',
    promptRepeat: 3,
    ipa: ['m', 'aɪ', 's', ''],
  },
];
