import { LearningWord } from '../types/learning-word.types';

export interface LearningWordFixture {
  id: string;
  word: string;
  promptLabel: string;
  accentColor: string;
  promptImage?: string;
  ipa: string[];
}

export const QUIZ_UNLOCK_THRESHOLD = 10;

export const LEARNING_WORDS: LearningWord[] = [
  {
    id: 'james',
    word: 'JAMES',
    promptLabel: 'James',
    accentColor: '#4A90E2',
    promptImage: '👦',
    ipa: ['dʒ', 'eɪ', 'm', '', 'z'],
  },
  {
    id: 'grandma',
    word: 'GRANDMA',
    promptLabel: 'Grandma',
    accentColor: '#C71585',
    promptImage: '👵',
    ipa: ['g', 'r', 'æ', 'n', 'd', 'm', 'ɑː'],
  },
  {
    id: 'granddad',
    word: 'GRANDDAD',
    promptLabel: 'Grandad',
    accentColor: '#6C3483',
    promptImage: '👴',
    ipa: ['g', 'r', 'æ', 'n', 'd', 'd', 'æ', 'd'],
  },
  {
    id: 'mummy',
    word: 'MUMMY',
    promptLabel: 'Mummy',
    accentColor: '#E91E63',
    promptImage: '👩',
    ipa: ['m', 'ʌ', 'm', 'm', 'iː'],
  },
  {
    id: 'daddy',
    word: 'DADDY',
    promptLabel: 'Daddy',
    accentColor: '#27AE60',
    promptImage: '👨',
    promptPhoto: '/images/words/daddy.jpg',
    ipa: ['d', 'æ', 'd', 'd', 'iː'],
  },
  {
    id: 'sarah',
    word: 'SARAH',
    promptLabel: 'Sarah',
    accentColor: '#D6336C',
    promptImage: '👩‍🏻',
    ipa: ['s', 'eə', 'r', 'ə'],
  },
  {
    id: 'baby',
    word: 'BABY',
    promptLabel: 'Baby',
    accentColor: '#FFB6C1',
    promptImage: '👶',
    ipa: ['b', 'eɪ', 'b', 'iː'],
  },
  {
    id: 'grandpa',
    word: 'GRANDPA',
    promptLabel: 'Grandpa',
    accentColor: '#8B4513',
    promptImage: '👨‍🦳',
    ipa: ['g', 'r', 'æ', 'n', 'p', 'ɑː'],
  },
  {
    id: 'granny',
    word: 'GRANNY',
    promptLabel: 'Granny',
    accentColor: '#8E4585',
    promptImage: '👩‍🦳',
    ipa: ['g', 'r', 'æ', 'n', 'n', 'iː'],
  },
  {
    id: 'meg',
    word: 'MEG',
    promptLabel: 'Meg',
    accentColor: '#A0522D',
    promptImage: '🐕‍🦺',
    ipa: ['m', 'e', 'g'],
  },
  {
    id: 'fox',
    word: 'FOX',
    promptLabel: 'Fox',
    accentColor: '#E67E22',
    promptImage: '🦊',
    ipa: ['f', 'ɒ', 'ks'],
  },
  {
    id: 'bed',
    word: 'BED',
    promptLabel: 'Bed',
    accentColor: '#8E44AD',
    promptImage: '🛏️',
    ipa: ['b', 'e', 'd'],
  },
  {
    id: 'milk',
    word: 'MILK',
    promptLabel: 'Milk',
    accentColor: '#F8F9FA',
    promptImage: '🥛',
    ipa: ['m', 'ɪ', 'l', 'k'],
  },
  {
    id: 'orange',
    word: 'ORANGE',
    promptLabel: 'Orange',
    accentColor: '#F39C12',
    promptImage: '🍊',
    ipa: ['ɒ', 'r', 'ɪ', 'n', 'dʒ'],
  },
  {
    id: 'banana',
    word: 'BANANA',
    promptLabel: 'Banana',
    accentColor: '#F1C40F',
    promptImage: '🍌',
    ipa: ['b', 'ə', 'n', 'ɑː', 'n', 'ə'],
  },
  {
    id: 'dog',
    word: 'DOG',
    promptLabel: 'Dog',
    accentColor: '#8D5524',
    promptImage: '🐶',
    ipa: ['d', 'ɒ', 'g'],
  },
  {
    id: 'cat',
    word: 'CAT',
    promptLabel: 'Cat',
    accentColor: '#F2994A',
    promptImage: '🐱',
    ipa: ['k', 'æ', 't'],
  },
  {
    id: 'bike',
    word: 'BIKE',
    promptLabel: 'Bike',
    accentColor: '#E67E22',
    promptImage: '🚲',
    ipa: ['b', 'aɪ', 'k', ''],
  },
  {
    id: 'book',
    word: 'BOOK',
    promptLabel: 'Book',
    accentColor: '#2980B9',
    promptImage: '📗',
    ipa: ['b', 'ʊ', 'k'],
  },
  {
    id: 'tractor',
    word: 'TRACTOR',
    promptLabel: 'Tractor',
    accentColor: '#F39C12',
    promptImage: '🚜',
    ipa: ['t', 'r', 'æ', 'k', 't', 'ə'],
  },
  {
    id: 'crane',
    word: 'CRANE',
    promptLabel: 'Crane',
    accentColor: '#E67E22',
    promptImage: '🏗️',
    ipa: ['k', 'r', 'eɪ', 'n', ''],
  },
  {
    id: 'apple',
    word: 'APPLE',
    promptLabel: 'Apple',
    accentColor: '#E74C3C',
    promptImage: '🍎',
    ipa: ['æ', 'p', 'l', ''],
  },
  {
    id: 'jam',
    word: 'JAM',
    promptLabel: 'Jam',
    accentColor: '#CB4335',
    promptImage: '🫙',
    ipa: ['dʒ', 'æ', 'm'],
  },
  {
    id: 'big',
    word: 'BIG',
    promptLabel: 'Big',
    accentColor: '#2C3E50',
    promptImage: '🦕',
    ipa: ['b', 'ɪ', 'g'],
  },
  {
    id: 'splash',
    word: 'SPLASH',
    promptLabel: 'Splash',
    accentColor: '#3498DB',
    promptImage: '💦',
    ipa: ['s', 'p', 'l', 'æ', 'ʃ'],
  },
  {
    id: 'rain',
    word: 'RAIN',
    promptLabel: 'Rain',
    accentColor: '#5DADE2',
    promptImage: '🌧️',
    ipa: ['r', 'eɪ', 'n'],
  },
  {
    id: 'games',
    word: 'GAMES',
    promptLabel: 'Games',
    accentColor: '#8E44AD',
    promptImage: '🎲',
    ipa: ['g', 'eɪ', 'm', '', 'z'],
  },
  {
    id: 'jigsaw',
    word: 'JIGSAW',
    promptLabel: 'Jigsaw',
    accentColor: '#D35400',
    promptImage: '🧩',
    ipa: ['dʒ', 'ɪ', 'g', 's', 'ɔː'],
  },
  {
    id: 'tram',
    word: 'TRAM',
    promptLabel: 'Tram',
    accentColor: '#16A085',
    promptImage: '🚊',
    ipa: ['t', 'r', 'æ', 'm'],
  },
  {
    id: 'train',
    word: 'TRAIN',
    promptLabel: 'Train',
    accentColor: '#2980B9',
    promptImage: '🚂',
    ipa: ['t', 'r', 'eɪ', 'n'],
  },
  {
    id: 'rail',
    word: 'RAIL',
    promptLabel: 'Rail',
    accentColor: '#7F8C8D',
    promptImage: '🛤️',
    ipa: ['r', 'eɪ', 'l'],
  },
  {
    id: 'track',
    word: 'TRACK',
    promptLabel: 'Track',
    accentColor: '#5D6D7E',
    promptImage: '🚆',
    ipa: ['t', 'r', 'æ', 'k'],
  },
];
