import { LearningWord } from '../types/learning-word.types';

export const LEARNING_WORDS: LearningWord[] = [
  {
    id: 'james',
    word: 'JAMES',
    promptLabel: 'James',
    accentColor: '#4A90E2',
    promptImage: '👦',
  },
  {
    id: 'grandma',
    word: 'GRANDMA',
    promptLabel: 'Grandma',
    accentColor: '#C71585',
    promptImage: '👵',
  },
  {
    id: 'granddad',
    word: 'GRANDDAD',
    promptLabel: 'Granddad',
    accentColor: '#6C3483',
    promptImage: '👴',
  },
  {
    id: 'mummy',
    word: 'MUMMY',
    promptLabel: 'Mummy',
    accentColor: '#E91E63',
    promptImage: '👩',
  },
  {
    id: 'daddy',
    word: 'DADDY',
    promptLabel: 'Daddy',
    accentColor: '#27AE60',
    promptImage: '👨',
  },
  {
    id: 'sarah',
    word: 'SARAH',
    promptLabel: 'Sarah',
    accentColor: '#D6336C',
    promptImage: '👩🏻',
  },
  {
    id: 'grandpa',
    word: 'GRANDPA',
    promptLabel: 'Grandpa',
    accentColor: '#8B4513',
    promptImage: '👨‍🦳',
  },
  {
    id: 'granny',
    word: 'GRANNY',
    promptLabel: 'Granny',
    accentColor: '#8E4585',
    promptImage: '👩‍🦳',
  },
  {
    id: 'meg',
    word: 'MEG',
    promptLabel: 'Meg',
    accentColor: '#A0522D',
    promptImage: '🐕‍🦺',
  },
  {
    id: 'cat',
    word: 'CAT',
    promptLabel: 'Cat',
    accentColor: '#F2994A',
    promptImage: '🐱',
  },
  {
    id: 'dog',
    word: 'DOG',
    promptLabel: 'Dog',
    accentColor: '#8D5524',
    promptImage: '🐶',
  },
  {
    id: 'bike',
    word: 'BIKE',
    promptLabel: 'Bike',
    accentColor: '#E67E22',
    promptImage: '🚲',
  },
  {
    id: 'book',
    word: 'BOOK',
    promptLabel: 'Book',
    accentColor: '#2980B9',
    promptImage: '📗',
  },
  {
    id: 'digger',
    word: 'DIGGER',
    promptLabel: 'Digger',
    accentColor: '#F39C12',
    promptImage: '🏗️',
  },
  {
    id: 'apple',
    word: 'APPLE',
    promptLabel: 'Apple',
    accentColor: '#E74C3C',
    promptImage: '🍎',
  },
  {
    id: 'jam',
    word: 'JAM',
    promptLabel: 'Jam',
    accentColor: '#CB4335',
    promptImage: '🫙',
  },
  {
    id: 'big',
    word: 'BIG',
    promptLabel: 'Big',
    accentColor: '#2C3E50',
    promptImage: '🦕',
  },
  {
    id: 'splash',
    word: 'SPLASH',
    promptLabel: 'Splash',
    accentColor: '#3498DB',
    promptImage: '💦',
  },
  {
    id: 'rain',
    word: 'RAIN',
    promptLabel: 'Rain',
    accentColor: '#5DADE2',
    promptImage: '🌧️',
  },
  {
    id: 'games',
    word: 'GAMES',
    promptLabel: 'Games',
    accentColor: '#8E44AD',
    promptImage: '🎲',
  },
  {
    id: 'jigsaw',
    word: 'JIGSAW',
    promptLabel: 'Jigsaw',
    accentColor: '#D35400',
    promptImage: '🧩',
  },
  {
    id: 'tram',
    word: 'TRAM',
    promptLabel: 'Tram',
    accentColor: '#16A085',
    promptImage: '🚊',
  },
  {
    id: 'train',
    word: 'TRAIN',
    promptLabel: 'Train',
    accentColor: '#2980B9',
    promptImage: '🚂',
  },
  {
    id: 'rail',
    word: 'RAIL',
    promptLabel: 'Rail',
    accentColor: '#7F8C8D',
    promptImage: '🛤️',
  },
  {
    id: 'track',
    word: 'TRACK',
    promptLabel: 'Track',
    accentColor: '#5D6D7E',
    promptImage: '🚆',
  },
  {
    id: 'engine',
    word: 'ENGINE',
    promptLabel: 'Engine',
    accentColor: '#1ABC9C',
    promptImage: '🚃',
  },
];
